In [ ]:
# Creation Library Of Math420 Introduction to Cryptology..

In [4]:
# Chaper 1 An Introduction to Cryptography

"""
Extenden Euclidean Algorithm
The equation au + bv = gcd(a, b) always has a solution in u and v,
this algorithm gives the solutions..
Algortihm returns (gcd(a,b), u, v) respectively in a tuple..
"""
def extendedEuclidean(a, b):
    # Write some information/explanition before putting the library
    u = 1
    g = a
    x = 0
    y = b
    while( y >= 0):
        if ( y == 0):            
            if ( b != 0):              # Fixing the issue of division by 0..
                v = (g - a * u) / b
            return (g, u, v)
        else:
            #Finding remainder
            t = g % y
            
            #Finding multiple
            q = g // y
        
            # Setting the values
            s = u - q * x
        
            u = x
            g = y
        
            x = s
            y = t

#Example use of Algorithm
print("(ii) (228, 1056) => (gcd, u, v) = ", extendedEuclidean(228,1258))


"""
Same Algortihm the only difference is that solutions of u is bigger then zero..

"""
def extendedEuclideanU(a, b):
    # Write some information/explanition before putting the library
    u = 1
    g = a
    x = 0
    y = b
    while( y >= 0):
        if ( y == 0):
            # Fixing the issue of division by 0..
            if ( b != 0):
                v = (g - a * u) / b
                
            # making u bigger than zero.. 
            u = u + (b / g)
            v = v - (a / g )
            return (g, u, v)
        else:
            #Finding remainder
            t = g % y
            #Finding multiple
            q = g // y
        
            # Setting the values
        
            s = u - q * x
        
            u = x
            g = y
        
            x = s
            y = t
            
#Example use of Algorithm
print("(ii) (228, 1056) => (gcd, u, v) = ", extendedEuclideanU(228,1258))


(ii) (228, 1056) => (gcd, u, v) =  (2, -160, 29)
(ii) (228, 1056) => (gcd, u, v) =  (2, 469, -85)


In [8]:
"""
The Fuction basicly calculates g^A (mod N) (N need not to be a prime)
Fuction takes modulo N, g and A as a parameters..
returns the result of calculation.
"""
def squareAndMultiply(N, g, A):
    # Setting the values
    a = g
    b = 1
    
    while ( A > 0):
        if( A % 2 == 1):
            b = (b * a) % N
        
        a = a^2 % N
        A = A//2
    return b

#Example use of Function.
print("11^507 mod(1237) =", squareAndMultiply(1237, 11, 507), ", Checking with sage's power_mod(g, A, N):", power_mod(11, 507, 1237))

11^507 mod(1237) = 322 , Checking with sage's power_mod(g, A, N): 322


In [ ]:
# retuns the prime factors witha a given number
def primeFactorsList(number):
    Factor = factor(number)
    Factor_list = [p for (p,m) in Factor] #for _ in range(m)]
    
    return Factor_list

# Finds all primitive root modulo p, p is a prime
# With the help of Euler's Phi Funtion..
def primitiveRoots(prime):
    # Attention! function assumes that p is prime..
    listOfPrimitiveRoots = []
    
    # Since we use prime number euler's phi function equals prime - 1..
    phi = prime - 1 
    
    primeFac = primeFactorsList(phi)
    
    for r in range ( 2, phi + 1):
        
        flag = False
        
        for it in primeFac:
            if (power_mod(r, phi//it, prime) == 1):
                
                flag = True
                break 
                
        if ( flag == False):
            listOfPrimitiveRoots.append(r)
        
    return listOfPrimitiveRoots

"""
For Part f of Exercise 1.34 i reorganized the primitiveRoots function a little
Now it checks whether if given root is a primitive root modulo p or not.. 
So it returns False/True
""" 
def isPrimitiveRoot( prime, root):
    # Attention! function assumes that p is prime..
    
    # Since we use prime number euler's phi function equals prime - 1..
    phi = prime - 1 
    
    primeFac = primeFactorsList(phi)
    
    for r in range ( 2, phi + 1):
        
        flag = False
        
        for it in primeFac:
            
            if ( power_mod(r, phi//it, prime) == 1):
                
                flag = True
                break 
                
        if ( flag == False):
            if ( root == r):
                return True
    return False


# Returns the all prime numbers for a given interval..
def primeList(start, end):
    list = []
    for counter in range( start, end + 1):
        if ( is_prime(counter)):
            list.append(counter)
    
    return list

In [ ]:
from math import ceil, sqrt
def bsgs(g, h, p):
    '''
    Solve for x in h = g^x mod p given a prime p.
    If p is not prime, you shouldn't use BSGS anyway.
    '''
    N = ceil(sqrt(p - 1))  # phi(p) is p-1 if p is prime

    # Store hashmap of g^{1...m} (mod p). Baby step.
    tbl = {pow(g, i, p): i for i in range(N)}

    # Precompute via Fermat's Little Theorem
    c = pow(g, N * (p - 2), p)

    # Search for an equivalence in the table. Giant step.
    for j in range(N):
        y = (h * pow(c, j, p)) % p
        if y in tbl:
            return j * N + tbl[y]

    # Solution not found
    return None


bsgs(2, 893, 1373)

In [ ]:
# Finds solution of g^x=h mod(p)
def dlpFinder(g, h, p):
    c = Mod(g,p)
    return discrete_log(h, c)

dlpFinder(650, 2213, 3571)

In [ ]:
E = EllipticCurve(GF(83), [0,0,0,19,17])
E.points()
E.cardinality()
P = E(1,28)
Q = E(11,48)

# For Discrete Log of Elliptic Curves..

n = P.discrete_log(Q)
print(n)

In [ ]:
## SUPERINCREASING CHECK - checks whether it is superincreasing or not

from sage.numerical.knapsack import Superincreasing
L = [3, 7, 19, 43, 89, 195]
Superincreasing(L).is_superincreasing()

In [ ]:
def subsetSumProblem(l, S):
    x_list = []
    x_list_f = []
    is_correct = False
    count = 0
    check = S
    
    for i in reversed(l):
        if S >= i:
            x_list.append(1)
            S = S - i
            count = count + i
        else:
            x_list.append(0)
            
    x_list.reverse()
    
    if check == count:
        is_correct = True
    return x_list, is_correct, count

la = [3, 7, 19, 43, 89, 195]
Sa = 260

lb = [5, 11, 25, 61, 125, 261]
Sb = 408

lc = [2, 5, 12, 28, 60, 131, 257]
Sc = 334

ld = [4, 12, 15, 36, 75, 162]
Sd = 214 

print(subsetSumProblem(la, Sa))
print(subsetSumProblem(lb, Sb))
print(subsetSumProblem(lc, Sc))
print(subsetSumProblem(ld, Sd))

In [1]:
#Gausian Lattice Reduction,, Solves 
import numpy as np

def gauss_reduction(v1, v2):
    while True:
        if np.dot(v2, v2) < np.dot(v1, v1):
            v1, v2 = v2, v1 # swap step
            #print(v1, v2)
        m = round( np.dot(v1,v2) / np.dot(v1,v1) )
        if m == 0:
            return (v1, v2)
        v2 = v2 - m*v1 # reduction step

v1 = np.array([66586820, 65354729])
v2 = np.array([6513996, 6393464])

print(gauss_reduction(v1, v2))

va1 = np.array([120670, 110521])
va2 = np.array([323572, 296358])

vb1 = np.array([174748650, 45604569])
vb2 = np.array([35462559, 9254748])

vc1 = np.array([725734520, 613807887])
vc2 = np.array([3433061338, 2903596381])

print(gauss_reduction(va1, va2))
print(gauss_reduction(vb1, vb2))
print(gauss_reduction(vc1, vc2))

(array([ 2280., -1001.]), array([-1324., -2376.]))
(array([ 14., -47.]), array([-362., -131.]))
(array([147., 330.]), array([ 690., -207.]))
(array([4690.,  126.]), array([2086., 4235.]))


In [ ]:
# Exercise 7.55..
q = 148059109201
h = 24201896593
e = 83493429501
L = Matrix(ZZ, [[1, h], [0, q]])
#L.LLL()


def gaussianReductionKey(h, q):
    L = Matrix(ZZ, [[1,h], [0, q]])
    return L.LLL()

gaussianReductionKey(h, q)

In [2]:
# Book's vers
def myLLL(M, S):
    L = Matrix(ZZ, len(M), len(M))
    
    for i in range(len(M)):
    
        L[i, i] = 2
        L[i, -1] = M[i]
    
    for j in range(len(M)):
        if j != len(M) - 1:
            L[len(M) - 1, j] = 1
        L[len(M)-1, len(M)-1] = S
    
        
    print(L)
    
    #LLL() form sage..
    #Attention.. Choose the row which have only zero's and one's.. (And The last one Should be zero..)
    #then implement with your knowledge..
    
    return L.LLL()

# Add S to the end of M( there is no time to fix it...)
S = 168296
M = (81946, 80956, 58407, 51650, 38136, 17032, 39658, 67468, 49203, 9546, S)
myLLL(M, S)

[     2      0      0      0      0      0      0      0      0      0  81946]
[     0      2      0      0      0      0      0      0      0      0  80956]
[     0      0      2      0      0      0      0      0      0      0  58407]
[     0      0      0      2      0      0      0      0      0      0  51650]
[     0      0      0      0      2      0      0      0      0      0  38136]
[     0      0      0      0      0      2      0      0      0      0  17032]
[     0      0      0      0      0      0      2      0      0      0  39658]
[     0      0      0      0      0      0      0      2      0      0  67468]
[     0      0      0      0      0      0      0      0      2      0  49203]
[     0      0      0      0      0      0      0      0      0      2   9546]
[     1      1      1      1      1      1      1      1      1      1 168296]


[ 1 -1  1  1 -1  1 -1  1  1 -1  0]
[ 1 -1  1  1 -1  1  1  1 -1  1  1]
[ 3  1  1  3  1  1  1 -3  1 -1  0]
[ 3  1  1 -1  3  1 -3  1  1  1  2]
[-2  0  2 -2  4  0  2  2  2  0  2]
[-2 -2  4 -4 -2  0  2  0  0 -2 -2]
[-1 -3 -1  1  1 -3 -3 -1  1  1  3]
[-2  2  0  4 -2 -4 -2  0  0  2 -2]
[-2  4  4  0 -2  2  0 -2  2  0  1]
[-4 -2  0  2  4  0  0  2 -4 -2  0]
[ 2  4  2  0 -2 -2 -2  2 -4 -4 -1]

In [ ]:
p=29
R.<x>=PolynomialRing(GF(p))
points=[(3,25), (6,20), (9,6), (12,12),(15,9),(18,26)]
f=R.lagrange_polynomial(points)
print(f)